### ISSUE TITLE
Make the "Join Me" CTA linkable

### ISSUE THREAD

**Issue by kexline4710** [chitechdiversity/Chi-Tech-Diversity-Site#12]
## Issue

The Join Me section is designed nicely, but is not clickable. We've received feedback that users are expecting to be directed to the sign up portion.
## Request

Make the "Join Me" call to action clickable. Clicking on it should direct the user to the sign up portion.

**Comment by alainakafkes** [comment]
I'll take this. :)

**Comment by BesuSatra** [comment]
Even i also want to work on this issue.

**Comment by amitsin6h** [comment]
@kexline4710 I want to work on this

**Comment by amitsin6h** [comment]
@ if pull request solves your issue please accept it :)

**Comment by kexline4710** [comment]
Thanks everyone. I accepted the first one submitted!
