### ISSUE TITLE
Change Code of Conduct to be new Community Covenant

### ISSUE THREAD

**Issue by kexline4710** [chitechdiversity/Chi-Tech-Diversity-Site#13]
## Issue

@CoralineAda developed a new [Coder Covenant](http://community-covenant.net/) that is awesome sauce.
## Request

Replace the copy in the sign up module with the text in this [Covenant](http://community-covenant.net/).

**Comment by vqm** [comment]
Update has been Merged :)

**Comment by vqm** [comment]
Update has been merged :)

**Comment by friscomm** [comment]
Can I dibs this one? :)

I can make a PR to change the Code of Conduct

**Comment by CoralineAda** [comment]
Go for it @friscomm !

**Comment by friscomm** [comment]
Actually it looks like it already matches the Code of Conduct found here:
http://community-covenant.net/version/1/0/

The only thing I noticed is a few sections that could use some up to date contact info:

`If you are being harassed by a member of our community, notice that someone else is being harassed, or have any other concerns, please contact the administrators via [INSERT APPROPRIATE CONTACT METHOD HERE].`

And

`The admin team will respond to any complaint as promptly as possible we can. If you do not get a timely response (for example, if no admins are currently online) then please put your personal safety and well-being first, and consider logging out and/or contacting the admins by email at [EMAIL ADDRESS HERE]`

If you'd know the info you'd like to put in those square brackets I can update that for you instead :)

Or let me know if I'm missing something and there need to be more changes made

**Comment by kexline4710** [comment]
An account was created an added for an immediate need. This is now resolved. Thanks to all who looked into this!
