### ISSUE TITLE
Change HTML Title to reflect page purpose

### ISSUE THREAD

**Issue by kexline4710** [chitechdiversity/Chi-Tech-Diversity-Site#20]
## Problem

This HTML title text currently says "Hello, World!" which can be seen in the browser tab when the page is open. This is legacy from the project this site was forked from.
## Solution

Change this to be "Chi Tech Diversity" and verify it works.

**Comment by rishirajjain** [comment]
I'm interested in doing this

**Comment by kexline4710** [comment]
Go for it! I typically to accept the first working PR.

**Comment by kexline4710** [comment]
Fixed by #21.
