### ISSUE TITLE
CAPTCHA  - The thing where I say I'm not a robot

### ISSUE THREAD

**Issue by lorenanicole** [chitechdiversity/Chi-Tech-Diversity-Site#4]

**Comment by kexline4710** [comment]
A few interesting ideas:
- http://www.sitepoint.com/honeypot-captcha/
- http://node.demo.visualcaptcha.net/

**Comment by kexline4710** [comment]
Follow progress in `feature/add_captcha_support`.

**Comment by kexline4710** [comment]
See: https://github.com/chitechdiversity/slack-invite-automation/pull/9

**Comment by kexline4710** [comment]
See #11.

**Comment by kexline4710** [comment]
Completed.
