### ISSUE TITLE
Create copy for website

### ISSUE THREAD

**Issue by lorenanicole** [chitechdiversity/Chi-Tech-Diversity-Site#6]
Proposed website outline --

JOIN
- Signup box with CAPTCHA and required checkbox to ensure that they read the Code of Conduct.

ABOUT
- About section with a description of what the group is about. Expect a ~2 sentence mission statement and maybe a 1-2 paragraph description.\
- A selection of the important channels and a one sentence description of what they are. Probably expect to feature 8 channels. (Ex. #general, #slack-help, #community-organizers, etc.)

RULES
- Code of Conduct section
- An etiquette section that contains a bullet point list of etiquette rules.

**Comment by lrakhman** [comment]
Hey Lorena, I just did the etiquette section. I'll email it to you now.

**Comment by kexline4710** [comment]
This has been completed.
